Repository OCBM/OCBM-FE, pull requests merged in 2023-12, with the labels that each got.

#45 Feature/ocbm 157 mastery element api integration
  src/pages/mastery/Element.tsx
  src/services/elementServices.ts
  src/utils/sitemap.ts
Labels: feature

#52 plant and machine line state cleared on edit
  src/pages/mastery/MachineLine.tsx
  src/pages/mastery/Plant.tsx
Labels: bug

#55 breadcrumbs fixed
  src/components/layout/index.tsx
  src/components/reusable/breadcrumbs/index.tsx
Labels: bug

#54 Code Refactor & Pagination design
  src/components/reusable/popupmodal/popupmodal.tsx
  src/components/reusable/popupmodal/types.tsx
  src/index.css
  src/main.tsx
  src/pages/mastery/Element.tsx
  src/pages/mastery/Machine.tsx
  src/pages/mastery/MachineLine.tsx
  src/pages/mastery/Plant.tsx
  src/pages/mastery/Shop.tsx
  src/pages/reports/index.tsx
  src/pages/users/DeleteUser.tsx
  src/pages/users/UsersList.tsx
  src/services/userServices.ts
  src/utils/theme.json
Labels: refactor

#49 Feature/ocbm 158 set standard
  src/App.tsx
  src/components/reusable/table/index.css
  src/pages/setStandards/SetStandardList.tsx
  src/pages/setStandards/SetStandardsCreate.tsx
  src/pages/setStandards/constants.ts
  src/pages/setStandards/index.css
  src/pages/setStandards/index.tsx
Labels: feature

#48 Feature/ocbm 159 set standard
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/index.tsx
  src/assets/icons/types.tsx
  src/components/reusable/breadcrumbs/index.tsx
  src/components/reusable/checkbox/index.tsx
  src/components/reusable/checkbox/types.tsx
  src/components/reusable/dropdown/index.tsx
  src/components/reusable/dropdown/types.ts
  src/components/reusable/index.ts
  src/index.css
  src/pages/setStandards/index.tsx
  src/pages/setStandards/newSetStandards.tsx
  src/utils/sitemap.ts
Labels: feature
